const skill = [
  "AI Engineer",
  "AutoCAD",
  "Automation Testing with QTP",
  "Automation Testing with Selenium",
  "Automobile Engineering",
  "AWS DevOps ",
  "Big Data",
  "C Language",
  "C# Developer",
  "C++",
  "Chemical Engineering",
  "Civil Engineering",
  "Core Java",
  "Cyber Security",
  "Data Analyst",
  "Data Science",
  "Electrical Engineering",
  "Electronics Engineering",
  "HTML, CSS, Javascript",
  "J2EE Developer",
  "Java Full Stack ",
  "Linux",
  "Machine Learning Engineer",
  "Manual Testing",
  "Mechanical Engineering",
  "Microsoft Azure DevOps ",
  "Mobile Application Developer",
  "Mongo DB",
  "MySQL",
  "Networking",
  "Node JS Developer",
  "Oracle SQL",
  "Petrochemical Engineering",
  "PHP",
  "Power BI",
  "Production Engineering",
  "Python",
  "Qlikview Developer",
  "React JS Developer",
  "Robotics Engineer",
  "Salesforce Developer",
  "SAP ABAP Developer",
  "Tableau Developer",
  "Technical Support Engineer",
];

export default skill;
